### ISSUE TITLE
Perl path

### ISSUE THREAD

**Issue by racke** [devcamps/camps#18]
With the current solutions for perl's local for the user (perlbrew), it would be much more appropriate to change the shebang to `#!/usr/bin/env perl`.

**Comment by racke** [comment]
I used the following script as workaround (with symlinks called mysql_camp, mkcamp to it):

```bash
#! /bin/bash

COMMAND=$(basename $0)
export PERL5LIB="/home/camp/camps/lib"
exec /usr/bin/env perl /home/camp/camps/bin/$COMMAND "$@"
```

**Comment by jonjensen** [comment]
Using env has its downside: Suddenly scripts that worked reliably all the time depend on the PATH environment variable set when invoking. But I'm willing to make the change and cope with that problem in other ways if you want to submit a patch in a pull request.

**Comment by racke** [comment]
PR done.
