### ISSUE TITLE
Unnecessary usage of system for copying file

### ISSUE THREAD

**Issue by racke** [devcamps/camps#22]
`do_system("cp -p $conf->{icroot}/src/vlink $conf->{cgidir}/$_")`

**Comment by SysPete** [comment]
In a similar vein the following can be handled using File::Find and File::Path which are both in core:
do_system(sprintf('find %s %s',  $_, q(-name '.svn' -type d -prune -exec rm -rf '{}' \\;)))

**Comment by jonjensen** [comment]
Patches welcome, as long as the results are identical!

**Comment by jonjensen** [comment]
Stefan, did you ever modify the camp system for this? If so, I'd love to look at merging it. Otherwise I'm going to close this because there isn't any bug.

**Comment by racke** [comment]
No, I never made a patch for this.
