### ISSUE TITLE
Hardcoded port numbers 

### ISSUE THREAD

**Issue by racke** [devcamps/camps#26]
The starting point for the port numbers is hardcoded:

Database port 8900 
HTTP port 9000
HTTPS port 9100
...

So I got a system where I can only access ports below 9100 and now I'm stuck
without changing the source code.

**Comment by jonjensen** [comment]
Making this configurable would be great. Nobody has needed it before, or else it would already be configurable. A patch would be welcome!

**Comment by jonjensen** [comment]
Stefan, did you ever modify the camp system for this? If so, I'd love to look at getting the change merged.
