### ISSUE TITLE
define IC socket path

### ISSUE THREAD

**Issue by sbatschelet** [devcamps/camps#27]
The IC socket path is statically set in Master.pm to var/run/socket.  While this is usually not a problem, users migrating sites to camps may find changing the socket path an unnecessary "optimization".  To solve this we will add a new config variable ic_socket_path which will default to var/run/socket.

**Comment by jonjensen** [comment]
Sam, have you done anything on this yet? Seems like it would be a simple change.

**Comment by sbatschelet** [comment]
@jonjensen  please review https://github.com/devcamps/camps/pull/30

**Comment by sbatschelet** [comment]
closed by PR #30
