### ISSUE TITLE
mkcamp restart before init.

### ISSUE THREAD

**Issue by hexfusion** [devcamps/camps#29]
This block seems wrong, we are restarting before we init the app.
## mkcamp

```
# (Re)start facilities
if ($opt{skipdb}) {
    print <<'END';
Of course, you specified --skipdb, so there may be no database, and
your app server is not running. It's up to you to deal with that.
END
}
else {
    server_control(
        service => 'all',
        action  => 'restart',
    );
    server_control(
        service => 'app',
        action  => 'init',
    ) if has_app();
}
```

**Comment by jonjensen** [comment]
@hexfusion Do you know of a case where this is causing trouble? If not, I'm inclined to leave it alone.

The users out there using the "init" option are a smaller subset of the total, and if it is working for them, it is likely intentional that things are done in this order.

**Comment by hexfusion** [comment]
@jonjensen I made the issue after seeing the problem in the wild as it was a few years ago I can not recall where. Closing.
